//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExampleDDD.Infraestructure.Data
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ExampleDDD.Domain.Entities;
    
    public partial class dbhotelEntities : DbContext
    {
        public dbhotelEntities()
            : base("name=dbhotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbpermission> tbpermission { get; set; }
    }//Fin de la clase parcial dbhotelEntities
}
